name: Update Quote Readme

on:
  workflow_dispatch:
  schedule:
    # Runs at 8 UTC everyday
    - cron: "0 8 * * *"

jobs:
  update-readme:
    name: Quote - README
    runs-on: ubuntu-latest
    steps:
      - uses: siddharth2016/quote-readme@0.1.2
            
